image: docker:17.06-rc

stages:
  - build
  - deploy
  - test

build:
  stage: build
  script:
    - cd kubernetes/fluentd && bash -x merge.sh ams01 out
    - cd kubernetes/fluentd && bash -x parse.sh out parsed ams01/fluentd-es-ams01.conf

test:
  stage: test
  script:
    - ls -l out
    - ls -l parsed
