image: fedora:25

stages:
  - build
  - deploy
  - test

before_script:
  - dnf -y install dnf-plugins-core
  - dnf -y config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
  - dnf -y config-manager --set-enabled docker-ce-edge
  - dnf -y config-manager --set-disabled docker-ce-edge
  - dnf -y makecache fast
  - dnf -y install docker-ce
  - systemctl start docker

build:
  stage: build
  script:
    - cd kubernetes/fluentd && bash -x merge.sh ams01 out
    - cd kubernetes/fluentd && bash -x parse.sh out parsed ams01/fluentd-es-ams01.conf

test:
  stage: test
  script:
    - ls -l out
    - ls -l parsed
