image: centos:7

stages:
  - build
  - deploy
  - test

before_script:
  - yum -y install git

build:
  stage: build
  script:
    - cd kubernetes/fluentd && merge.sh ams01 out
    - cd kubernetes/fluentd && parse.sh out parsed ams01/fluentd-es-ams01.conf

test:
  stage: test
  script:
    - ls -l out
    - ls -l parsed
