image: erwinnttdata/merge-jinja2-yaml:latest

stages:
  - build

build:
  stage: build
  script:
    - cd kubernetes/fluentd
    - bash -x merge.sh ams01 out
    - bash -x parse.sh out parsed ams01/fluentd-es-ams01.conf
    - ls -l out
    - ls -l parsed
